import { v4 as uuidv4 } from 'uuid';

export const MOCK_WATCHES = [
  {
    id: uuidv4(),
    serialNumber: 'RLX-SUB-2023-001234',
    brand: 'Rolex',
    model: 'Submariner Date',
    referenceNumber: '126610LN',
    yearOfProduction: 2023,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    braceletMaterial: 'Oystersteel',
    movement: 'Calibre 3235',
    waterResistance: '300m',
    estimatedValue: 12500,
    purchasePrice: 11800,
    purchaseDate: new Date('2023-06-15').toISOString(),
    purchaseLocation: 'Official Rolex Boutique, Geneva',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: true,
    warrantyExpirationDate: new Date('2028-06-15').toISOString(),
    condition: 'Excellent',
    images: ['/watch-1.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0x1234567890abcdef1234567890abcdef12345678',
    createdAt: new Date('2023-06-16').toISOString(),
    updatedAt: new Date('2023-06-16').toISOString(),
    caseDiameter: '41mm',
    powerReserve: '70 heures',
    bezelMaterial: 'Ceramic',
    documents: ['Certificat original', 'Carte de garantie', 'Facture d\'achat'],
    lastServiceDate: new Date('2024-11-10').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'PP-NAU-2022-005678',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    referenceNumber: '5711/1A-010',
    yearOfProduction: 2022,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    braceletMaterial: 'Stainless Steel',
    movement: 'Calibre 26-330 S C',
    waterResistance: '120m',
    estimatedValue: 95000,
    purchasePrice: 32000,
    purchaseDate: new Date('2022-03-10').toISOString(),
    purchaseLocation: 'Patek Philippe Boutique, Paris',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: true,
    warrantyExpirationDate: new Date('2024-03-10').toISOString(),
    condition: 'Mint',
    images: ['/watch-2.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0xabcdef1234567890abcdef1234567890abcdef12',
    createdAt: new Date('2022-03-11').toISOString(),
    updatedAt: new Date('2022-03-11').toISOString(),
    caseDiameter: '40mm',
    powerReserve: '45 heures',
    bezelMaterial: 'Steel',
    documents: ['Certificat PP', 'Extract des Archives', 'Boîte complète'],
    lastServiceDate: new Date('2024-05-10').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'AP-RO-2021-009876',
    brand: 'Audemars Piguet',
    model: 'Royal Oak',
    referenceNumber: '15500ST.OO.1220ST.01',
    yearOfProduction: 2021,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    braceletMaterial: 'Stainless Steel',
    movement: 'Calibre 4302',
    waterResistance: '50m',
    estimatedValue: 62000,
    purchasePrice: 28000,
    purchaseDate: new Date('2021-11-20').toISOString(),
    purchaseLocation: 'AP Boutique, New York',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: false,
    condition: 'Very Good',
    images: ['/watch-3.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0x9876543210fedcba9876543210fedcba98765432',
    createdAt: new Date('2021-11-21').toISOString(),
    updatedAt: new Date('2021-11-21').toISOString(),
    caseDiameter: '41mm',
    powerReserve: '70 heures',
    bezelMaterial: 'Steel',
    documents: ['Certificat AP', 'Garantie expirée'],
    lastServiceDate: new Date('2023-06-15').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'OMG-SPD-2020-445566',
    brand: 'Omega',
    model: 'Speedmaster Professional',
    referenceNumber: '310.30.42.50.01.001',
    yearOfProduction: 2020,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    braceletMaterial: 'Stainless Steel',
    movement: 'Calibre 1861',
    waterResistance: '50m',
    estimatedValue: 6500,
    purchasePrice: 5800,
    purchaseDate: new Date('2020-08-15').toISOString(),
    purchaseLocation: 'Omega Boutique, London',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: false,
    condition: 'Good',
    images: ['/watch-4.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0xfedcba9876543210fedcba9876543210fedcba98',
    createdAt: new Date('2020-08-16').toISOString(),
    updatedAt: new Date('2020-08-16').toISOString(),
    caseDiameter: '42mm',
    powerReserve: '48 heures',
    bezelMaterial: 'Aluminum',
    documents: ['Certificat Omega', 'Manuel d\'utilisation'],
    lastServiceDate: new Date('2022-09-20').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'CAR-MON-2024-778899',
    brand: 'Cartier',
    model: 'Santos de Cartier',
    referenceNumber: 'WSSA0029',
    yearOfProduction: 2024,
    caseMaterial: 'Steel',
    dialColor: 'Silver',
    braceletMaterial: 'Steel',
    movement: 'Calibre 1847 MC',
    waterResistance: '100m',
    estimatedValue: 7200,
    purchasePrice: 7200,
    purchaseDate: new Date('2024-02-14').toISOString(),
    purchaseLocation: 'Cartier Boutique, Dubai',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: true,
    warrantyExpirationDate: new Date('2032-02-14').toISOString(),
    condition: 'Mint',
    images: ['/watch-5.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0x112233445566778899aabbccddeeff0011223344',
    createdAt: new Date('2024-02-15').toISOString(),
    updatedAt: new Date('2024-02-15').toISOString(),
    caseDiameter: '39.8mm',
    powerReserve: '42 heures',
    bezelMaterial: 'Steel',
    documents: ['Certificat international', 'Garantie 8 ans', 'Écrin Cartier'],
  },
  {
    id: uuidv4(),
    serialNumber: 'TAG-CAR-2019-334455',
    brand: 'TAG Heuer',
    model: 'Carrera Chronograph',
    referenceNumber: 'CBN2A1A.BA0643',
    yearOfProduction: 2019,
    caseMaterial: 'Steel',
    dialColor: 'Black',
    braceletMaterial: 'Steel',
    movement: 'Calibre Heuer 02',
    waterResistance: '100m',
    estimatedValue: 5200,
    purchasePrice: 4800,
    purchaseDate: new Date('2019-12-10').toISOString(),
    purchaseLocation: 'TAG Heuer, Monaco',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: false,
    condition: 'Very Good',
    images: ['/watch-6.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0xaabbccdd11223344556677889900ffeeddccbbaa',
    createdAt: new Date('2019-12-11').toISOString(),
    updatedAt: new Date('2019-12-11').toISOString(),
    caseDiameter: '44mm',
    powerReserve: '80 heures',
    bezelMaterial: 'Ceramic',
    documents: ['Certificat TAG', 'Manuel'],
  },
];

export const MOCK_WATCH_HISTORY = [
  {
    watchId: MOCK_WATCHES[0].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Certification initiale et enregistrement blockchain',
        performedBy: 'Veritas Expert Paris',
        eventDate: new Date('2023-06-16').toISOString(),
        blockchainHash: MOCK_WATCHES[0].blockchainHash,
        createdAt: new Date('2023-06-16').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Révision complète atelier Rolex certifié',
        performedBy: 'Rolex Service Center Geneva',
        eventDate: new Date('2024-11-10').toISOString(),
        notes: 'Étanchéité testée, mouvement nettoyé et régulé, bracelet poli',
        createdAt: new Date('2024-11-10').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'valuation',
        description: 'Expertise et réévaluation de marché',
        performedBy: 'Expert Veritas',
        eventDate: new Date('2025-01-15').toISOString(),
        notes: 'Valeur augmentée en raison de la rareté croissante',
        createdAt: new Date('2025-01-15').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'inspection',
        description: 'Contrôle de sécurité annuel',
        performedBy: 'Veritas Lab',
        eventDate: new Date('2025-06-16').toISOString(),
        notes: 'Tous les composants vérifiés authentiques',
        createdAt: new Date('2025-06-16').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[1].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'purchase',
        description: 'Achat boutique officielle Patek Philippe',
        performedBy: 'PP Boutique Paris',
        eventDate: new Date('2022-03-10').toISOString(),
        notes: 'Montre neuve avec liste d\'attente de 2 ans',
        createdAt: new Date('2022-03-10').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Enregistrement initial blockchain',
        performedBy: 'test-user-123',
        eventDate: new Date('2022-03-11').toISOString(),
        blockchainHash: MOCK_WATCHES[1].blockchainHash,
        createdAt: new Date('2022-03-11').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'transfer',
        description: 'Transfert de propriété vérifié',
        performedBy: 'Jean Dupont',
        eventDate: new Date('2023-01-20').toISOString(),
        notes: 'Vente privée avec certificat d\'authenticité',
        createdAt: new Date('2023-01-20').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Service complet Patek Philippe Geneva',
        performedBy: 'PP Service Center',
        eventDate: new Date('2024-05-10').toISOString(),
        notes: 'Mouvement nettoyé, régulé et testé durant 15 jours',
        createdAt: new Date('2024-05-10').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'valuation',
        description: 'Réévaluation exceptionnelle',
        performedBy: 'Christie\'s Geneva',
        eventDate: new Date('2024-09-15').toISOString(),
        notes: 'Valeur triplée depuis l\'achat - modèle discontinué',
        createdAt: new Date('2024-09-15').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[2].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Authentification par experts AP',
        performedBy: 'test-user-123',
        eventDate: new Date('2021-11-21').toISOString(),
        blockchainHash: MOCK_WATCHES[2].blockchainHash,
        createdAt: new Date('2021-11-21').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Entretien annuel',
        performedBy: 'AP Service NY',
        eventDate: new Date('2022-11-10').toISOString(),
        notes: 'Remplacement joints, test étanchéité OK',
        createdAt: new Date('2022-11-10').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'inspection',
        description: 'Inspection d\'authenticité de routine',
        performedBy: 'AP Service Center',
        eventDate: new Date('2023-06-15').toISOString(),
        notes: 'Tous composants vérifiés comme authentiques',
        createdAt: new Date('2023-06-15').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Polissage professionnel',
        performedBy: 'AP Master Polisher',
        eventDate: new Date('2024-03-20').toISOString(),
        notes: 'Polissage complet bracelet et boîtier',
        createdAt: new Date('2024-03-20').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[3].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'purchase',
        description: 'Achat boutique Omega Londres',
        performedBy: 'Omega Boutique London',
        eventDate: new Date('2020-08-15').toISOString(),
        createdAt: new Date('2020-08-15').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Certification Veritas',
        performedBy: 'test-user-123',
        eventDate: new Date('2020-08-16').toISOString(),
        blockchainHash: MOCK_WATCHES[3].blockchainHash,
        createdAt: new Date('2020-08-16').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Révision mécanique complète',
        performedBy: 'Omega Service',
        eventDate: new Date('2022-09-20').toISOString(),
        notes: 'Révision du mouvement 1861, chronographe calibré',
        createdAt: new Date('2022-09-20').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[4].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'purchase',
        description: 'Achat boutique Cartier Dubai',
        performedBy: 'Cartier Dubai Mall',
        eventDate: new Date('2024-02-14').toISOString(),
        notes: 'Cadeau Saint-Valentin',
        createdAt: new Date('2024-02-14').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Enregistrement blockchain immédiat',
        performedBy: 'test-user-123',
        eventDate: new Date('2024-02-15').toISOString(),
        blockchainHash: MOCK_WATCHES[4].blockchainHash,
        createdAt: new Date('2024-02-15').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[5].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'purchase',
        description: 'Achat TAG Heuer Monaco',
        performedBy: 'TAG Boutique Monaco',
        eventDate: new Date('2019-12-10').toISOString(),
        createdAt: new Date('2019-12-10').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Certification Veritas',
        performedBy: 'test-user-123',
        eventDate: new Date('2019-12-11').toISOString(),
        blockchainHash: MOCK_WATCHES[5].blockchainHash,
        createdAt: new Date('2019-12-11').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Service mouvement manufacture',
        performedBy: 'TAG Service',
        eventDate: new Date('2023-01-10').toISOString(),
        notes: 'Calibre Heuer 02 révisé',
        createdAt: new Date('2023-01-10').toISOString(),
      },
    ],
  },
];

export const MOCK_TRANSFERS = [
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[1].id,
    fromUserId: 'test-user-123',
    toUserId: null,
    transferToken: 'TRF-DEMO-' + Date.now(),
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    status: 'pending',
    expiresAt: new Date(Date.now() + 2 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: uuidv4(),
    title: 'Révision programmée',
    message: 'Votre Rolex Submariner nécessite une révision dans 30 jours',
    type: 'reminder',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Valeur augmentée',
    message: 'Le Patek Philippe Nautilus a pris +8% de valeur ce mois-ci',
    type: 'valuation',
    read: false,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uuidv4(),
    title: 'Certificat mis à jour',
    message: 'Nouveau certificat blockchain généré pour Royal Oak',
    type: 'document',
    read: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_MARKET_TRENDS = {
  rolex: { change: +12.4, trend: 'up', avgPrice: 15200 },
  patekPhilippe: { change: +28.7, trend: 'up', avgPrice: 89000 },
  audemarsPiguet: { change: +5.2, trend: 'up', avgPrice: 58000 },
  omega: { change: +2.1, trend: 'up', avgPrice: 6800 },
  cartier: { change: +3.5, trend: 'up', avgPrice: 7500 },
  tagHeuer: { change: -1.2, trend: 'down', avgPrice: 5000 },
};

export const MOCK_USERS = [
  {
    id: 'test-user-123',
    email: 'test@watchpassport.com',
    firstName: 'Jean',
    lastName: 'Martin',
    userType: 'collector',
    kycStatus: 'verified',
    kycVerifiedAt: new Date('2023-01-15').toISOString(),
    phoneNumber: '+33 6 12 34 56 78',
    country: 'France',
    city: 'Paris',
    avatar: null,
    createdAt: new Date('2023-01-15').toISOString(),
    updatedAt: new Date('2025-11-20').toISOString(),
  },
  {
    id: 'user-456',
    email: 'sophie.durand@gmail.com',
    firstName: 'Sophie',
    lastName: 'Durand',
    userType: 'dealer',
    kycStatus: 'verified',
    kycVerifiedAt: new Date('2022-05-10').toISOString(),
    phoneNumber: '+41 22 123 45 67',
    country: 'Switzerland',
    city: 'Geneva',
    avatar: null,
    createdAt: new Date('2022-05-10').toISOString(),
    updatedAt: new Date('2025-11-15').toISOString(),
  },
  {
    id: 'user-789',
    email: 'marc.bernard@watchcollector.fr',
    firstName: 'Marc',
    lastName: 'Bernard',
    userType: 'collector',
    kycStatus: 'verified',
    kycVerifiedAt: new Date('2024-03-20').toISOString(),
    phoneNumber: '+33 1 45 67 89 01',
    country: 'France',
    city: 'Lyon',
    avatar: null,
    createdAt: new Date('2024-03-20').toISOString(),
    updatedAt: new Date('2025-11-10').toISOString(),
  },
];

export const MOCK_STOLEN_REPORTS = [
  {
    id: uuidv4(),
    watchId: uuidv4(), // Not one of the current user's watches
    serialNumber: 'RLX-DAY-2018-998877',
    brand: 'Rolex',
    model: 'Day-Date 40',
    reportedBy: 'user-456',
    reporterName: 'Sophie Durand',
    stolenDate: new Date('2025-10-15').toISOString(),
    stolenLocation: 'Geneva, Switzerland',
    policeReportNumber: 'GE-2025-10-4567',
    description: 'Montre volée lors d\'un cambriolage, boîtier en or jaune 18k, cadran champagne',
    status: 'active',
    blockchainHash: '0xstolenwatch1234567890abcdef',
    createdAt: new Date('2025-10-16').toISOString(),
    updatedAt: new Date('2025-10-16').toISOString(),
  },
  {
    id: uuidv4(),
    watchId: uuidv4(),
    serialNumber: 'PP-CAL-2020-445566',
    brand: 'Patek Philippe',
    model: 'Calatrava',
    reportedBy: 'user-789',
    reporterName: 'Marc Bernard',
    stolenDate: new Date('2025-09-03').toISOString(),
    stolenLocation: 'Paris, France',
    policeReportNumber: 'PRS-2025-09-1234',
    description: 'Vol à l\'arraché, montre en or blanc avec bracelet cuir',
    status: 'active',
    blockchainHash: '0xstolenwatch9876543210fedcba',
    createdAt: new Date('2025-09-04').toISOString(),
    updatedAt: new Date('2025-09-04').toISOString(),
  },
];

export const MOCK_SERVICE_PROVIDERS = [
  {
    id: uuidv4(),
    name: 'Rolex Service Center Geneva',
    type: 'official',
    brands: ['Rolex'],
    location: 'Geneva, Switzerland',
    address: 'Rue de la Servette 3-5, 1211 Geneva',
    phone: '+41 22 302 22 00',
    email: 'service@rolex.com',
    certifications: ['Rolex Certified', 'COSC'],
    rating: 5.0,
    reviewCount: 1247,
    verified: true,
  },
  {
    id: uuidv4(),
    name: 'Patek Philippe Service Center',
    type: 'official',
    brands: ['Patek Philippe'],
    location: 'Geneva, Switzerland',
    address: 'Chemin du Pont-du-Centenaire 141, 1228 Plan-les-Ouates',
    phone: '+41 22 884 20 20',
    email: 'service@patek.com',
    certifications: ['PP Certified', 'Geneva Seal'],
    rating: 5.0,
    reviewCount: 892,
    verified: true,
  },
  {
    id: uuidv4(),
    name: 'Veritas Expert Paris',
    type: 'independent',
    brands: ['Rolex', 'Patek Philippe', 'Audemars Piguet', 'Omega', 'Cartier', 'TAG Heuer'],
    location: 'Paris, France',
    address: '25 Place Vendôme, 75001 Paris',
    phone: '+33 1 42 60 00 00',
    email: 'contact@veritas-expert.fr',
    certifications: ['WOSTEP Certified', 'AMI Certified'],
    rating: 4.9,
    reviewCount: 2156,
    verified: true,
  },
];

export const MOCK_INSURANCE_POLICIES = [
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[0].id, // Rolex Submariner
    provider: 'AXA Art Insurance',
    policyNumber: 'AXA-WATCH-2023-001234',
    coverageAmount: 15000,
    premium: 180,
    paymentFrequency: 'annual',
    startDate: new Date('2023-07-01').toISOString(),
    endDate: new Date('2024-07-01').toISOString(),
    renewalDate: new Date('2024-07-01').toISOString(),
    coverage: ['theft', 'loss', 'damage', 'mysterious disappearance'],
    deductible: 250,
    status: 'active',
    createdAt: new Date('2023-06-20').toISOString(),
    updatedAt: new Date('2023-06-20').toISOString(),
  },
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[1].id, // Patek Philippe Nautilus
    provider: 'Chubb Collectors Insurance',
    policyNumber: 'CHUBB-COLL-2022-005678',
    coverageAmount: 120000,
    premium: 1440,
    paymentFrequency: 'annual',
    startDate: new Date('2022-04-01').toISOString(),
    endDate: new Date('2025-04-01').toISOString(),
    renewalDate: new Date('2025-04-01').toISOString(),
    coverage: ['theft', 'loss', 'damage', 'mysterious disappearance', 'worldwide coverage'],
    deductible: 1000,
    status: 'active',
    createdAt: new Date('2022-03-15').toISOString(),
    updatedAt: new Date('2022-03-15').toISOString(),
  },
];

export const MOCK_AUCTION_RESULTS = [
  {
    id: uuidv4(),
    auctionHouse: 'Christie\'s Geneva',
    auctionDate: new Date('2025-05-15').toISOString(),
    brand: 'Rolex',
    model: 'Submariner Date',
    referenceNumber: '126610LN',
    year: 2023,
    condition: 'Excellent',
    hammerPrice: 13200,
    estimateLow: 11000,
    estimateHigh: 14000,
    lotNumber: 125,
    result: 'sold',
  },
  {
    id: uuidv4(),
    auctionHouse: 'Sotheby\'s Hong Kong',
    auctionDate: new Date('2025-04-20').toISOString(),
    brand: 'Patek Philippe',
    model: 'Nautilus',
    referenceNumber: '5711/1A-010',
    year: 2021,
    condition: 'Mint',
    hammerPrice: 98000,
    estimateLow: 80000,
    estimateHigh: 120000,
    lotNumber: 234,
    result: 'sold',
  },
  {
    id: uuidv4(),
    auctionHouse: 'Phillips Geneva',
    auctionDate: new Date('2025-06-01').toISOString(),
    brand: 'Audemars Piguet',
    model: 'Royal Oak',
    referenceNumber: '15500ST.OO.1220ST.01',
    year: 2021,
    condition: 'Very Good',
    hammerPrice: 65000,
    estimateLow: 55000,
    estimateHigh: 70000,
    lotNumber: 78,
    result: 'sold',
  },
  {
    id: uuidv4(),
    auctionHouse: 'Antiquorum New York',
    auctionDate: new Date('2025-03-10').toISOString(),
    brand: 'Omega',
    model: 'Speedmaster Professional',
    referenceNumber: '310.30.42.50.01.001',
    year: 2020,
    condition: 'Good',
    hammerPrice: 6800,
    estimateLow: 6000,
    estimateHigh: 7500,
    lotNumber: 456,
    result: 'sold',
  },
];

export const MOCK_CERTIFICATIONS = [
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[0].id,
    certificateNumber: 'CERT-RLX-2023-001234',
    issuedBy: 'Veritas Expert Paris',
    issuerType: 'independent',
    certificationDate: new Date('2023-06-16').toISOString(),
    expiryDate: new Date('2028-06-16').toISOString(),
    authenticityVerified: true,
    conditionGrade: 'A+',
    estimatedValue: 12500,
    notes: 'Authentification complète avec tests non-destructifs, analyse spectroscopique des matériaux',
    blockchainHash: MOCK_WATCHES[0].blockchainHash,
    documentUrl: '/certificates/cert-rlx-001234.pdf',
    createdAt: new Date('2023-06-16').toISOString(),
  },
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[1].id,
    certificateNumber: 'CERT-PP-2022-005678',
    issuedBy: 'Patek Philippe Service Center',
    issuerType: 'official',
    certificationDate: new Date('2024-05-10').toISOString(),
    expiryDate: new Date('2029-05-10').toISOString(),
    authenticityVerified: true,
    conditionGrade: 'A++',
    estimatedValue: 95000,
    notes: 'Certificat officiel Patek Philippe avec Extract des Archives',
    blockchainHash: MOCK_WATCHES[1].blockchainHash,
    documentUrl: '/certificates/cert-pp-005678.pdf',
    createdAt: new Date('2024-05-10').toISOString(),
  },
];

export const MOCK_PORTFOLIO_STATS = {
  totalValue: MOCK_WATCHES.reduce((sum, watch) => sum + watch.estimatedValue, 0),
  totalPurchasePrice: MOCK_WATCHES.reduce((sum, watch) => sum + watch.purchasePrice, 0),
  totalAppreciation: 0, // Will be calculated
  appreciationPercentage: 0, // Will be calculated
  numberOfWatches: MOCK_WATCHES.length,
  averageWatchValue: 0, // Will be calculated
  mostValuableWatch: MOCK_WATCHES[1], // Patek Philippe
  newestWatch: MOCK_WATCHES[4], // Cartier Santos
  oldestWatch: MOCK_WATCHES[5], // TAG Heuer
  brandDistribution: {
    Rolex: 1,
    'Patek Philippe': 1,
    'Audemars Piguet': 1,
    Omega: 1,
    Cartier: 1,
    'TAG Heuer': 1,
  },
};

// Calculate derived stats
MOCK_PORTFOLIO_STATS.totalAppreciation = MOCK_PORTFOLIO_STATS.totalValue - MOCK_PORTFOLIO_STATS.totalPurchasePrice;
MOCK_PORTFOLIO_STATS.appreciationPercentage = ((MOCK_PORTFOLIO_STATS.totalAppreciation / MOCK_PORTFOLIO_STATS.totalPurchasePrice) * 100);
MOCK_PORTFOLIO_STATS.averageWatchValue = MOCK_PORTFOLIO_STATS.totalValue / MOCK_PORTFOLIO_STATS.numberOfWatches;

export const MOCK_WATCH_COMPARISONS = [
  {
    id: uuidv4(),
    brand: 'Rolex',
    model: 'Submariner Date',
    referenceNumber: '126610LN',
    userWatch: MOCK_WATCHES[0],
    marketData: {
      lowestPrice: 11200,
      averagePrice: 12500,
      highestPrice: 14800,
      numberOfSales: 156,
      priceRange: '11.2K - 14.8K €',
      condition: 'All conditions',
      dataSource: 'WatchCharts',
      lastUpdated: new Date('2025-11-20').toISOString(),
    },
  },
  {
    id: uuidv4(),
    brand: 'Patek Philippe',
    model: 'Nautilus',
    referenceNumber: '5711/1A-010',
    userWatch: MOCK_WATCHES[1],
    marketData: {
      lowestPrice: 85000,
      averagePrice: 95000,
      highestPrice: 125000,
      numberOfSales: 45,
      priceRange: '85K - 125K €',
      condition: 'Mint to Excellent',
      dataSource: 'Chrono24',
      lastUpdated: new Date('2025-11-19').toISOString(),
    },
  },
];

export const MOCK_SERVICE_REMINDERS = [
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[0].id,
    reminderType: 'service',
    title: 'Révision programmée',
    description: 'Votre Rolex Submariner nécessite une révision complète tous les 5 ans',
    dueDate: new Date('2029-11-10').toISOString(),
    urgency: 'normal',
    dismissed: false,
    createdAt: new Date('2024-11-10').toISOString(),
  },
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[3].id,
    reminderType: 'service',
    title: 'Service recommandé',
    description: 'Omega Speedmaster - Dernière révision il y a 3 ans',
    dueDate: new Date('2025-09-20').toISOString(),
    urgency: 'high',
    dismissed: false,
    createdAt: new Date('2022-09-20').toISOString(),
  },
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[1].id,
    reminderType: 'insurance',
    title: 'Renouvellement assurance',
    description: 'Votre police d\'assurance Chubb arrive à expiration',
    dueDate: new Date('2025-04-01').toISOString(),
    urgency: 'high',
    dismissed: false,
    createdAt: new Date('2024-12-01').toISOString(),
  },
];

export const MOCK_ACTIVITY_FEED = [
  {
    id: uuidv4(),
    type: 'valuation_increase',
    title: 'Valeur augmentée',
    description: 'Patek Philippe Nautilus +€5,000 (+5.6%)',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    watchId: MOCK_WATCHES[1].id,
    icon: '📈',
  },
  {
    id: uuidv4(),
    type: 'service_completed',
    title: 'Service terminé',
    description: 'Rolex Submariner - Révision complète effectuée',
    timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    watchId: MOCK_WATCHES[0].id,
    icon: '🔧',
  },
  {
    id: uuidv4(),
    type: 'certificate_issued',
    title: 'Nouveau certificat',
    description: 'Certificat blockchain mis à jour pour Royal Oak',
    timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    watchId: MOCK_WATCHES[2].id,
    icon: '📜',
  },
  {
    id: uuidv4(),
    type: 'market_alert',
    title: 'Alerte marché',
    description: 'Les prix Rolex Submariner ont augmenté de 3% ce mois',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    watchId: MOCK_WATCHES[0].id,
    icon: '🔔',
  },
  {
    id: uuidv4(),
    type: 'watch_added',
    title: 'Montre ajoutée',
    description: 'Cartier Santos de Cartier ajouté à votre collection',
    timestamp: new Date('2024-02-15').toISOString(),
    watchId: MOCK_WATCHES[4].id,
    icon: '⌚',
  },
];

export const getMockWatchHistory = (watchId: string) => {
  const history = MOCK_WATCH_HISTORY.find(h => h.watchId === watchId);
  return history ? history.events : [];
};

