import { v4 as uuidv4 } from 'uuid';

export const MOCK_WATCHES = [
  {
    id: uuidv4(),
    serialNumber: 'RLX-SUB-2023-001234',
    brand: 'Rolex',
    model: 'Submariner Date',
    referenceNumber: '126610LN',
    yearOfProduction: 2023,
    caseMaterial: 'Oystersteel',
    dialColor: 'Black',
    braceletMaterial: 'Oystersteel',
    movement: 'Calibre 3235',
    waterResistance: '300m',
    estimatedValue: 12500,
    purchasePrice: 11800,
    purchaseDate: new Date('2023-06-15').toISOString(),
    purchaseLocation: 'Official Rolex Boutique, Geneva',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: true,
    warrantyExpirationDate: new Date('2028-06-15').toISOString(),
    condition: 'Excellent',
    images: ['/watch-1.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0x1234567890abcdef1234567890abcdef12345678',
    createdAt: new Date('2023-06-16').toISOString(),
    updatedAt: new Date('2023-06-16').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'PP-NAU-2022-005678',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    referenceNumber: '5711/1A-010',
    yearOfProduction: 2022,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    braceletMaterial: 'Stainless Steel',
    movement: 'Calibre 26-330 S C',
    waterResistance: '120m',
    estimatedValue: 95000,
    purchasePrice: 32000,
    purchaseDate: new Date('2022-03-10').toISOString(),
    purchaseLocation: 'Patek Philippe Boutique, Paris',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: true,
    warrantyExpirationDate: new Date('2024-03-10').toISOString(),
    condition: 'Mint',
    images: ['/watch-2.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0xabcdef1234567890abcdef1234567890abcdef12',
    createdAt: new Date('2022-03-11').toISOString(),
    updatedAt: new Date('2022-03-11').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'AP-RO-2021-009876',
    brand: 'Audemars Piguet',
    model: 'Royal Oak',
    referenceNumber: '15500ST.OO.1220ST.01',
    yearOfProduction: 2021,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    braceletMaterial: 'Stainless Steel',
    movement: 'Calibre 4302',
    waterResistance: '50m',
    estimatedValue: 62000,
    purchasePrice: 28000,
    purchaseDate: new Date('2021-11-20').toISOString(),
    purchaseLocation: 'AP Boutique, New York',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: false,
    condition: 'Very Good',
    images: ['/watch-3.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0x9876543210fedcba9876543210fedcba98765432',
    createdAt: new Date('2021-11-21').toISOString(),
    updatedAt: new Date('2021-11-21').toISOString(),
  },
  {
    id: uuidv4(),
    serialNumber: 'OMG-SPD-2020-445566',
    brand: 'Omega',
    model: 'Speedmaster Professional',
    referenceNumber: '310.30.42.50.01.001',
    yearOfProduction: 2020,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    braceletMaterial: 'Stainless Steel',
    movement: 'Calibre 1861',
    waterResistance: '50m',
    estimatedValue: 6500,
    purchasePrice: 5800,
    purchaseDate: new Date('2020-08-15').toISOString(),
    purchaseLocation: 'Omega Boutique, London',
    certificateOfAuthenticity: true,
    boxAndPapers: true,
    warrantyValid: false,
    condition: 'Good',
    images: ['/watch-4.jpg'],
    status: 'certified',
    currentOwnerId: 'test-user-123',
    blockchainHash: '0xfedcba9876543210fedcba9876543210fedcba98',
    createdAt: new Date('2020-08-16').toISOString(),
    updatedAt: new Date('2020-08-16').toISOString(),
  },
];

export const MOCK_WATCH_HISTORY = [
  {
    watchId: MOCK_WATCHES[0].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Watch certified and registered on blockchain',
        performedBy: 'test-user-123',
        eventDate: new Date('2023-06-16').toISOString(),
        blockchainHash: MOCK_WATCHES[0].blockchainHash,
        createdAt: new Date('2023-06-16').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Regular maintenance performed at authorized service center',
        performedBy: 'test-user-123',
        eventDate: new Date('2024-06-10').toISOString(),
        notes: 'Full service, water resistance tested, movement regulated',
        createdAt: new Date('2024-06-10').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'valuation',
        description: 'Professional appraisal and valuation',
        performedBy: 'Expert Veritas',
        eventDate: new Date('2025-01-15').toISOString(),
        notes: 'Market value increased due to scarcity',
        createdAt: new Date('2025-01-15').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[1].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Initial certification and blockchain registration',
        performedBy: 'test-user-123',
        eventDate: new Date('2022-03-11').toISOString(),
        blockchainHash: MOCK_WATCHES[1].blockchainHash,
        createdAt: new Date('2022-03-11').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'transfer',
        description: 'Ownership transferred from previous collector',
        performedBy: 'Jean Dupont',
        eventDate: new Date('2023-01-20').toISOString(),
        notes: 'Private sale with authentication certificate',
        createdAt: new Date('2023-01-20').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'service',
        description: 'Complete service at Patek Philippe Geneva',
        performedBy: 'Patek Philippe Service',
        eventDate: new Date('2024-05-10').toISOString(),
        notes: 'Movement cleaned, regulated, and tested',
        createdAt: new Date('2024-05-10').toISOString(),
      },
    ],
  },
  {
    watchId: MOCK_WATCHES[2].id,
    events: [
      {
        id: uuidv4(),
        eventType: 'certification',
        description: 'Certified authentic by AP experts',
        performedBy: 'test-user-123',
        eventDate: new Date('2021-11-21').toISOString(),
        blockchainHash: MOCK_WATCHES[2].blockchainHash,
        createdAt: new Date('2021-11-21').toISOString(),
      },
      {
        id: uuidv4(),
        eventType: 'inspection',
        description: 'Routine authenticity inspection',
        performedBy: 'AP Service Center',
        eventDate: new Date('2023-06-15').toISOString(),
        notes: 'All components verified as genuine',
        createdAt: new Date('2023-06-15').toISOString(),
      },
    ],
  },
];

export const MOCK_TRANSFERS = [
  {
    id: uuidv4(),
    watchId: MOCK_WATCHES[1].id,
    fromUserId: 'test-user-123',
    toUserId: null,
    transferToken: 'TRF-DEMO-' + Date.now(),
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    status: 'pending',
    expiresAt: new Date(Date.now() + 2 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const getMockWatchHistory = (watchId: string) => {
  const history = MOCK_WATCH_HISTORY.find(h => h.watchId === watchId);
  return history ? history.events : [];
};
